name: redq
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.2.4
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision=0.12.0
  - nvidia::cudatoolkit=11.3.1
  - joblib=1.1.0
  - pip:
    - gym[mujoco,robotics]==0.24.1
